--- 
document: 
  description: "Questa documentazione rientra nell’ambito del Cloud Enablement Kit, insieme di metodi, strumenti e buone pratiche che le pubbliche amministrazioni possono utilizzare per la migrazione al cloud di infrastrutture e servizi."
  name: "Manuale di abilitazione al cloud"
  tags: 
    - cloud
    - "Cloud Enablement Program"
    - "Manuale di abilitazione al cloud"
    - "Cloud enablement"
