--- 
document: 
  description: "La strategia Cloud della PA è nata per favorire l’adozione del modello cloud computing nelle pubbliche amministrazioni italiane, in linea con le indicazioni della strategia per la crescita digitale nell’ambito della nuova versione del Piano Triennale per l’informatica pubblica 2019-2021 e con le migliori pratiche nel resto dei principali paesi europei e del mondo."
  name: "Cloud Enablement Program"
  tags: 
    - cloud
    - "Cloud Enablement Program"
